[package]
name = "opendeck-infobar-utils"
authors = ["evilbug"]
license = "GPL-3.0-or-later"
edition = "2024"

[dependencies]
openaction = "2.6"
log = "0.4"
simplelog = "0.12"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.48", features = ["full"] }
chrono = "0.4"
image = { version = "0.25", default-features = false, features = ["png"] }
imageproc = { version = "0.26", default-features = false, features = ["text"] }
ab_glyph = "0.2"
base64 = "0.22"
reqwest = { version = "0.12", features = ["json"] }
